import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { MdHome, MdKitchen, MdCheckroom, MdWork, MdCalculate, MdContentCopy } from 'react-icons/md';
import { FaCalculator } from 'react-icons/fa';
import Header from '../components/Layout/Header';
import Footer from '../components/Layout/Footer';
import SEO from '../components/SEO';
import { seoData } from '../config/seoData';
import { calculateEstimate, formatCurrency } from '../config/pricing';
import './Calculator.css';

const Calculator = () => {
  const [selectedService, setSelectedService] = useState('');
  const [area, setArea] = useState('');
  const [complexity, setComplexity] = useState('standard');
  const [location, setLocation] = useState('tier2');
  const [timeline, setTimeline] = useState('normal');
  const [estimate, setEstimate] = useState(null);
  const [showAdvanced, setShowAdvanced] = useState(false);

  const services = [
    {
      id: 'full-home-interior',
      icon: MdHome,
      title: 'Full Home Interior',
      description: 'Complete home interior design and execution',
      features: ['Living room design', 'Bedroom interiors', 'Kitchen design', 'Bathroom design', 'Lighting design', 'Furniture selection'],
      color: '#546736'
    },
    {
      id: 'kitchen',
      icon: MdKitchen,
      title: 'Kitchen Interior',
      description: 'Complete kitchen design and modular solutions',
      features: ['Modular kitchen design', 'Cabinet installation', 'Countertop selection', 'Appliance integration', 'Lighting setup', 'Storage optimization'],
      color: '#7c4530'
    },
    {
      id: 'wardrobe',
      icon: MdCheckroom,
      title: 'Wardrobe Design',
      description: 'Custom wardrobe design and installation',
      features: ['Custom wardrobe design', 'Premium materials', 'Space optimization', 'Installation service', 'Hardware selection', 'Maintenance guide'],
      color: '#546736'
    }
  ];

  const handleServiceSelect = (service) => {
    // Navigate to respective calculator pages
    if (service.id === 'full-home-interior') {
      window.location.href = '/estimate/full-home-interior';
    } else if (service.id === 'kitchen') {
      window.location.href = '/estimate/kitchen-interior';
    } else if (service.id === 'wardrobe') {
      window.location.href = '/estimate/wardrobe-design';
    }
  };

  const handleCalculate = () => {
    if (!selectedService || !area) {
      alert('Please select a service and enter the area');
      return;
    }

    const areaNum = parseFloat(area);
    if (areaNum <= 0) {
      alert('Please enter a valid area');
      return;
    }

    const result = calculateEstimate(selectedService.id, areaNum, complexity, location, timeline);
    setEstimate(result);
  };

  const handleReset = () => {
    setSelectedService('');
    setArea('');
    setComplexity('standard');
    setLocation('tier2');
    setTimeline('normal');
    setEstimate(null);
    setShowAdvanced(false);
  };

  const copyEstimate = () => {
    if (estimate) {
      const estimateText = `Estimate for ${selectedService.title}:
Area: ${area} sq ft
Complexity: ${complexity.charAt(0).toUpperCase() + complexity.slice(1)}
Location: ${location.charAt(0).toUpperCase() + location.slice(1)} City
Timeline: ${timeline.charAt(0).toUpperCase() + timeline.slice(1)}

Base Cost: ${formatCurrency(estimate.baseAmount)}
Additional Charges: ${formatCurrency(estimate.additionalCharges)}
Total Estimate: ${formatCurrency(estimate.finalAmount)}

Generated by Dimension Dzine Calculator`;
      
      navigator.clipboard.writeText(estimateText);
      alert('Estimate copied to clipboard!');
    }
  };

  return (
    <>
      <SEO
        title={seoData.calculator.title}
        description={seoData.calculator.description}
        keywords={seoData.calculator.keywords}
        canonical={seoData.calculator.canonical}
        schema={seoData.calculator.schema}
        ogImage="/images/og-calculator.jpg"
      />
      <div className="page-wrapper">
        <Header />
      <main className="main-wrapper">
        {/* Hero Section */}
        <section className="calculator-hero">
          <div className="calculator-hero-content">
            <div className="calculator-hero-text">
              <h1 className="calculator-main-title">Advanced Project Cost Calculator</h1>
              <p className="calculator-subtitle">
                Get detailed estimates for your interior design projects. Our advanced calculator considers multiple factors to provide accurate pricing.
              </p>
              <div className="calculator-note">
                <p><strong>Note:</strong> This is an estimated cost. Final pricing will be provided after detailed consultation and site visit.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Service Selection */}
        <section className="calculator-service-selection">
          <div className="calculator-container">
            <div className="section-header">
              <h2>Select Your Service</h2>
              <p>Choose the type of interior design service you need</p>
            </div>
            
            <div className="service-selection-grid">
              {services.map((service) => {
                const IconComponent = service.icon;
                return (
                  <div
                    key={service.id}
                    className={`service-selection-card ${selectedService?.id === service.id ? 'selected' : ''}`}
                    onClick={() => handleServiceSelect(service)}
                  >
                    <div className="service-card-header">
                      <div className="service-icon-wrapper" style={{ backgroundColor: `${service.color}20` }}>
                        <IconComponent className="service-icon" style={{ color: service.color }} />
                      </div>
                      <div className="calculator-badge">
                        <FaCalculator />
                      </div>
                    </div>
                    
                    <div className="service-card-content">
                      <h3 className="service-title">{service.title}</h3>
                      <p className="service-description">{service.description}</p>
                      <div className="service-features">
                        {service.features.slice(0, 3).map((feature, index) => (
                          <span key={index} className="feature-item">
                            • {feature}
                          </span>
                        ))}
                      </div>
                    </div>
                    
                    <div className="service-card-action">
                      <button className="select-service-btn" style={{ backgroundColor: service.color }}>
                        CALCULATE &gt;
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* Calculator Form */}
        {selectedService && (
          <section className="calculator-form-section">
            <div className="calculator-container">
              <div className="form-card">
                <div className="form-header">
                  <h3>Calculate Your {selectedService.title}</h3>
                  <p>Provide project details to get your personalized estimate</p>
                </div>
                
                <div className="form-content">
                  <div className="form-grid">
                    <div className="form-group">
                      <label>Area (sq ft) *</label>
                      <input
                        type="number"
                        value={area}
                        onChange={(e) => setArea(e.target.value)}
                        placeholder="e.g., 1200"
                        min="1"
                        required
                      />
                    </div>
                    
                    <div className="form-group">
                      <label>Complexity Level</label>
                      <select value={complexity} onChange={(e) => setComplexity(e.target.value)}>
                        <option value="basic">Basic - Standard materials, simple design</option>
                        <option value="standard">Standard - Quality materials, modern design</option>
                        <option value="premium">Premium - High-end materials, custom design</option>
                        <option value="luxury">Luxury - Premium materials, bespoke design</option>
                      </select>
                    </div>
                    
                    <div className="form-group">
                      <label>Location</label>
                      <select value={location} onChange={(e) => setLocation(e.target.value)}>
                        <option value="tier1">Tier 1 City (Mumbai, Delhi, Bangalore)</option>
                        <option value="tier2">Tier 2 City (Pune, Hyderabad, Chennai)</option>
                        <option value="tier3">Tier 3 City (Other cities)</option>
                      </select>
                    </div>
                    
                    <div className="form-group">
                      <label>Project Timeline</label>
                      <select value={timeline} onChange={(e) => setTimeline(e.target.value)}>
                        <option value="urgent">Urgent (1-2 months)</option>
                        <option value="normal">Normal (3-6 months)</option>
                        <option value="flexible">Flexible (6+ months)</option>
                      </select>
                    </div>
                  </div>
                  
                  <div className="form-actions">
                    <button className="calculate-btn" onClick={handleCalculate}>
                      <MdCalculate className="btn-icon" />
                      Calculate Estimate
                    </button>
                    <button className="reset-btn" onClick={handleReset}>
                      Reset Form
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </section>
        )}

        {/* Estimate Results */}
        {estimate && (
          <section className="estimate-results-section">
            <div className="calculator-container">
              <div className="estimate-results-card">
                <div className="results-header">
                  <h3>Your Detailed Estimate</h3>
                  <p>Based on {selectedService.title} - {area} sq ft</p>
                </div>
                
                <div className="estimate-main-display">
                  <div className="total-amount">
                    <span className="amount">{formatCurrency(estimate.finalAmount)}</span>
                    <span className="amount-label">Total Estimated Cost</span>
                  </div>
                  
                  <div className="estimate-breakdown">
                    <div className="breakdown-section">
                      <h4>Cost Breakdown</h4>
                      <div className="breakdown-items">
                        <div className="breakdown-item">
                          <span>Base Cost ({area} sq ft × ₹{estimate.breakdown.basePricePerSqFt})</span>
                          <span>{formatCurrency(estimate.baseAmount)}</span>
                        </div>
                        <div className="breakdown-item">
                          <span>Additional Charges</span>
                          <span>{formatCurrency(estimate.additionalCharges)}</span>
                        </div>
                        <div className="breakdown-item total">
                          <span>Total Estimate</span>
                          <span>{formatCurrency(estimate.finalAmount)}</span>
                        </div>
                      </div>
                    </div>
                    
                    <div className="breakdown-section">
                      <h4>Applied Multipliers</h4>
                      <div className="multiplier-items">
                        <div className="multiplier-item">
                          <span>Complexity ({complexity})</span>
                          <span>{estimate.breakdown.complexityMultiplier}x</span>
                        </div>
                        <div className="multiplier-item">
                          <span>Location ({location})</span>
                          <span>{estimate.breakdown.locationMultiplier}x</span>
                        </div>
                        <div className="multiplier-item">
                          <span>Timeline ({timeline})</span>
                          <span>{estimate.breakdown.timelineMultiplier}x</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                
                <div className="estimate-actions">
                  <Link to="/contact" className="contact-btn">
                    <MdWork className="btn-icon" />
                    Get Detailed Quote
                  </Link>
                  <button className="copy-btn" onClick={copyEstimate}>
                    <MdContentCopy className="btn-icon" />
                    Copy Estimate
                  </button>
                  <button className="new-calc-btn" onClick={handleReset}>
                    <FaCalculator className="btn-icon" />
                    New Calculation
                  </button>
                </div>
                
                <div className="estimate-disclaimer">
                  <p>
                    <strong>Disclaimer:</strong> This is an approximate estimate based on current market rates and standard practices. 
                    Final costs may vary based on specific requirements, material choices, site conditions, and design complexity. 
                    Contact us for a detailed consultation and accurate quotation.
                  </p>
                </div>
              </div>
            </div>
          </section>
        )}


        {/* CTA Section */}
        <section className="calculator-cta-section">
          <div className="calculator-container">
            <div className="cta-content">
              <h2>Ready to Start Your Project?</h2>
              <p>Get in touch with our experts for a detailed consultation and accurate pricing.</p>
              <div className="cta-buttons">
                <Link to="/contact" className="cta-primary">
                  <MdWork className="btn-icon" />
                  Contact Us
                </Link>
                <Link to="/projects" className="cta-secondary">
                  <MdHome className="btn-icon" />
                  View Our Work
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
    </>
  );
};

export default Calculator;